spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration
  datasource:
    platform: postgres
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5435/gb?currentSchema=university
      username: postgres
      password: password
  jpa:
    database: POSTGRESQL
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop #validate
        jdbc:
          lob:
            non_contextual_creation: true
